[tool.poetry]
name = "griptape"
version = "0.18.2"
description = "Modular Python framework for LLM workflows, tools, memory, and data."
authors = ["Griptape <hello@griptape.ai>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/griptape-ai/griptape"

packages = [
    {include = "griptape"}
]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = ">=0.21"
openai = ">=0.27"
cohere = ">=4"
attrs = ">=22"
jinja2 = ">=3.1"
jsonschema = ">=4"
marshmallow = ">=3"
marshmallow-enum = ">=1.5"
tiktoken = ">=0.3"
rich = ">=13"
stopit = "*"
transformers = "^4.30"
huggingface-hub = ">=0.13"
schema = ">=0.7"
pyyaml = ">=6"
fastapi = ">=0.80"
uvicorn = ">= 0.20"
python-decouple=">=3"
boto3 = "^1.28.57"
tenacity = ">=8.0"
numpy = ">=1"
pinecone-client = ">=2"
marqo = ">=1.1.0"
PyPDF2 = ">=3"
trafilatura = ">= 1.6"
anthropic = "^0.3.0"
sqlalchemy = "~=1.0"
sqlalchemy-redshift = "*"
snowflake-sqlalchemy = "^1.4.7"
pymongo= "*"
redis = "^4.6.0"
opensearch-py = "^2.3.1"
stringcase = "^1.2.0"
docker = "^6.1.3"
requests-aws4auth = "1.2.3"
pandas = "^2.1.0"
pgvector = "^0.2.3"
psycopg2-binary = "^2.9.9"
snowflake-connector-python = "^3.2"
cryptography = "^41.0.4"
dateparser = "^1.1.8"


[tool.poetry.group.test.dependencies]
pytest = "~=7.1"
pytest-mock = "*"
mongomock = "*"

twine = ">=4"
moto = {extras = ["dynamodb"], version = "^4.1.8"}
pytest-xdist = "^3.3.1"
pytest-cov = "^4.1.0"
fuzzywuzzy = "^0.18.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.286"
black = "^23.7.0"
pyright = "^1.1.324"

[tool.black]
line-length=80

[tool.ruff]
line-length=80

[tool.pyright]
include = ["griptape"]
exclude = [
    "**/__pycache__",
]
pythonVersion = "3.9"
reportOptionalMemberAccess = "none"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
